[package]
name = "sublonk"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_middleware = { path = "../halo2_middleware" }
halo2_backend = { path = "../halo2_backend" }
halo2_frontend = { path = "../halo2_frontend" }
halo2_proofs = { path = "../halo2_proofs" }
halo2curves = { version = "0.6.1", default-features = false }
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }

ark-bn254 = "0.4.0"
ark-ff = { version = "0.4.2", features = ["parallel"] }
ark-ec = { version = "0.4.2", features = ["parallel"] }
ark-std = { version = "0.4.0", features = ["parallel"] }
ark-poly = { version = "0.4.0", features = ["parallel"] }
ark-segmentlookup = { git = "https://github.com/txaty/ark-segmentlookup.git", branch ="main" }
rayon = "1.10.0"