use std::marker::PhantomData;

use halo2curves::bn256::{Bn256, Fr, G1Affine};
use rand_core::OsRng;

use halo2_backend::plonk::{ProvingKey, VerifyingKey};
use halo2_backend::plonk::verifier::verify_proof;
use halo2_backend::poly::commitment::ParamsProver;
use halo2_backend::poly::kzg::commitment::{KZGCommitmentScheme, ParamsKZG};
use halo2_backend::poly::kzg::multiopen::{ProverSHPLONK, VerifierSHPLONK};
use halo2_backend::poly::kzg::strategy::SingleStrategy;
use halo2_backend::transcript::{Blake2bRead, Blake2bWrite, Challenge255, TranscriptReadBuffer, TranscriptWriterBuffer};
use halo2_frontend::plonk::Assigned;
use halo2_middleware::multicore::current_num_threads;
use halo2_proofs::{
    arithmetic::Field,
    circuit::{AssignedCell, Chip, Layouter, Region, SimpleFloorPlanner, Value},
    plonk::{Advice, Circuit, Column, ConstraintSystem, ErrorFront, Selector},
    poly::Rotation,
};
use halo2_proofs::plonk::{create_proof, keygen_pk, keygen_vk};

// ANCHOR: instructions
trait NumericInstructions<F: Field>: Chip<F> {
    /// Returns `c = a * b`.
    fn mul(
        &self,
        layouter: impl Layouter<F>,
        a: Value<Assigned<F>>,
        b: Value<Assigned<F>>,
    ) -> Result<(), ErrorFront>;
}
// ANCHOR_END: instructions

// ANCHOR: chip
/// The chip that will implement our instructions! Chips store their own
/// config, as well as type markers if necessary.
struct FieldChip<F: Field> {
    config: FieldConfig,
    _marker: PhantomData<F>,
}
// ANCHOR_END: chip

// ANCHOR: chip-config
/// Chip state is stored in a config struct. This is generated by the chip
/// during configuration, and then stored inside the chip.
#[derive(Clone, Debug)]
struct FieldConfig {
    /// For this chip, we will use two advice columns to implement our instructions.
    /// These are also the columns through which we communicate with other parts of
    /// the circuit.
    advice: [Column<Advice>; 3],

    // We need a selector to enable the multiplication gate, so that we aren't placing
    // any constraints on cells where `NumericInstructions::mul` is not being used.
    // This is important when building larger circuits, where columns are used by
    // multiple sets of instructions.
    s_mul: Selector,
}

impl<F: Field> FieldChip<F> {
    fn construct(config: <Self as Chip<F>>::Config) -> Self {
        Self {
            config,
            _marker: PhantomData,
        }
    }

    fn configure(
        meta: &mut ConstraintSystem<F>,
        advice: [Column<Advice>; 3],
    ) -> <Self as Chip<F>>::Config {
        for column in &advice {
            meta.enable_equality(*column);
        }
        let s_mul = meta.selector();

        // Define our multiplication gate!
        meta.create_gate("mul", |meta| {
            // To implement multiplication, we need three advice cells and a selector
            // cell. We arrange them like so:
            //
            // | a0  | a1  | s_mul |
            // |-----|-----|-------|
            // | lhs | rhs | s_mul |
            // | out |     |       |
            //
            // Gates may refer to any relative offsets we want, but each distinct
            // offset adds a cost to the proof. The most common offsets are 0 (the
            // current row), 1 (the next row), and -1 (the previous row), for which
            // `Rotation` has specific constructors.
            let lhs = meta.query_advice(advice[0], Rotation::cur());
            let rhs = meta.query_advice(advice[1], Rotation::cur());
            let out = meta.query_advice(advice[2], Rotation::cur());
            let s_mul = meta.query_selector(s_mul);

            // Finally, we return the polynomial expressions that constrain this gate.
            // For our multiplication gate, we only need a single polynomial constraint.
            //
            // The polynomial expressions returned from `create_gate` will be
            // constrained by the proving system to equal zero. Our expression
            // has the following properties:
            // - When s_mul = 0, any value is allowed in lhs, rhs, and out.
            // - When s_mul != 0, this constrains lhs * rhs = out.
            vec![s_mul * (lhs * rhs - out)]
        });

        FieldConfig {
            advice,
            s_mul,
        }
    }
}
// ANCHOR_END: chip-config

// ANCHOR: chip-impl
impl<F: Field> Chip<F> for FieldChip<F> {
    type Config = FieldConfig;
    type Loaded = ();

    fn config(&self) -> &Self::Config {
        &self.config
    }

    fn loaded(&self) -> &Self::Loaded {
        &()
    }
}
// ANCHOR_END: chip-impl

// ANCHOR: instructions-impl
/// A variable representing a number.
#[derive(Clone)]
struct Number<F: Field>(AssignedCell<F, F>);

impl<F: Field> NumericInstructions<F> for FieldChip<F> {
    fn mul(
        &self,
        mut layouter: impl Layouter<F>,
        a: Value<Assigned<F>>,
        b: Value<Assigned<F>>,
    ) -> Result<(), ErrorFront> {
        let config = self.config();

        layouter.assign_region(
            || "mul",
            |mut region: Region<'_, F>| {
                // We only want to use a single multiplication gate in this region,
                // so we enable it at region offset 0; this means it will constrain
                // cells at offsets 0 and 1.
                config.s_mul.enable(&mut region, 0)?;

                // The inputs we've been given could be located anywhere in the circuit,
                // but we can only rely on relative offsets inside this region. So we
                // assign new cells inside the region and constrain them to have the
                // same values as the inputs.
                // a.0.copy_advice(|| "lhs", &mut region, config.advice[0], 0)?;
                // b.0.copy_advice(|| "rhs", &mut region, config.advice[1], 0)?;
                region.assign_advice(|| "lhs", config.advice[0], 0, || a)?;
                region.assign_advice(|| "rhs", config.advice[1], 0, || b)?;

                // Now we can assign the multiplication result, which is to be assigned
                // into the output position.
                // let value = a.0.value().copied() * b.0.value();
                let value = a * b;

                // Finally, we do the assignment to the output, returning a
                // variable to be used in another part of the circuit.
                region
                    .assign_advice(|| "lhs * rhs", config.advice[2], 0, || value)?;

                Ok(())
            },
        )
    }
}

#[derive(Default)]
struct MyCircuit<F: Field> {
    a: Value<F>,
    b: Value<F>,
}

const NUM_GATES: i32 = 64 * 1024;

impl<F: Field> Circuit<F> for MyCircuit<F> {
    type Config = FieldConfig;
    type FloorPlanner = SimpleFloorPlanner;
    #[cfg(feature = "circuit-params")]
    type Params = ();

    fn without_witnesses(&self) -> Self {
        Self::default()
    }

    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Config {
        let advice = [meta.advice_column(), meta.advice_column(), meta.advice_column()];

        FieldChip::configure(meta, advice)
    }

    fn synthesize(
        &self,
        config: Self::Config,
        mut layouter: impl Layouter<F>,
    ) -> Result<(), ErrorFront> {
        let field_chip = FieldChip::<F>::construct(config);

        let a: Value<Assigned<_>> = self.a.into();
        let b: Value<Assigned<_>> = self.b.into();

        for _ in 0..NUM_GATES {
            field_chip.mul(layouter.namespace(|| "a * b"), a, b)?;
        }

        Ok(())
    }
}
// ANCHOR_END: circuit

fn keygen(k: u32) -> (ParamsKZG<Bn256>, ProvingKey<G1Affine>) {
    let params: ParamsKZG<Bn256> = ParamsKZG::<Bn256>::new(k);

    let empty_circuit: MyCircuit<Fr> = MyCircuit {
        a: Value::unknown(),
        b: Value::unknown(),
    };
    let vk = keygen_vk(&params, &empty_circuit).expect("keygen_vk should not fail");
    let pk = keygen_pk(&params, vk, &empty_circuit).expect("keygen_pk should not fail");

    (params, pk)
}

fn prover(params: &ParamsKZG<Bn256>, pk: &ProvingKey<G1Affine>, a: Fr, b: Fr) -> Vec<u8> {
    let rng = OsRng;

    let circuit: MyCircuit<Fr> = MyCircuit {
        a: Value::known(a),
        b: Value::known(b),
    };

    let mut transcript = Blake2bWrite::<Vec<u8>, G1Affine, Challenge255<G1Affine>>::init(vec![]);
    create_proof::<
        KZGCommitmentScheme<Bn256>,
        ProverSHPLONK<Bn256>,
        Challenge255<G1Affine>,
        OsRng,
        Blake2bWrite<Vec<u8>, G1Affine, Challenge255<G1Affine>>,
        MyCircuit<Fr>,
    >(params, pk, &[circuit], &[&[]], rng, &mut transcript)
        .expect("proof generation should not fail");

    transcript.finalize()
}

fn verifier(params: &ParamsKZG<Bn256>, vk: &VerifyingKey<G1Affine>, proof: &[u8]) {
    let params_verifier = params.verifier_params();
    let strategy = SingleStrategy::new(&params_verifier);
    let mut transcript = Blake2bRead::<&[u8], G1Affine, Challenge255<G1Affine>>::init(proof);
    assert!(verify_proof::<
        KZGCommitmentScheme<Bn256>,
        VerifierSHPLONK<Bn256>,
        Challenge255<G1Affine>,
        Blake2bRead::<&[u8], G1Affine, Challenge255<G1Affine>>,
        SingleStrategy<Bn256>,
    >(&params_verifier, vk, strategy, &[&[]], &mut transcript)
        .is_ok());
}

fn main() {
    let k: u32 = 7 + 10;

    println!("{}", current_num_threads());
    println!("k: {}", k);
    println!("num_gates: {}", NUM_GATES);
    println!("keygen start");
    let curr_time = std::time::Instant::now();
    let (params, pk) = keygen(k);
    println!("keygen time: {:?}", curr_time.elapsed());

    for i in 0..5 {
        println!("prover start, iter: {}", i + 1);
        let a = Fr::random(&mut OsRng);
        let b = Fr::random(&mut OsRng);

        let curr_time = std::time::Instant::now();
        let proof = prover(&params, &pk, a, b);
        println!("prover time: {:?}", curr_time.elapsed());

        verifier(&params, pk.get_vk(), proof.as_ref());
    }


    // use plotters::prelude::*;
    // let root = BitMapBackend::new("layout.png", (1024, 768)).into_drawing_area();
    // root.fill(&WHITE).unwrap();
    // let root = root
    //     .titled("My Circuit Layout", ("sans-serif", 60))
    //     .unwrap();
    //
    // let a = Fr::from(2);
    // let b = Fr::from(3);
    // let circuit = MyCircuit {
    //     a: Value::known(a),
    //     b: Value::known(b),
    // };
    //
    // halo2_proofs::dev::CircuitLayout::default()
    //     // You can optionally render only a section of the circuit.
    //     .view_width(0..5)
    //     .view_height(0..8)
    //     // You can hide labels, which can be useful with smaller areas.
    //     .show_labels(true)
    //     .show_equality_constraints(true)
    //     .mark_equality_cells(true)
    //     // Render the circuit onto your area!
    //     // The first argument is the size parameter for the circuit.
    //     .render(7, &circuit, &root)
    //     .unwrap();
}
